trigger:
- master

pool:
  name: 'AGENTS-158'
  #name: 'E-Commerce'


steps:
- task: replacetokens@3
  displayName: 'Replace tokens in Dockerfile'
  inputs:
    rootDirectory: '$(System.DefaultWorkingDirectory)'
    targetFiles: 'Dockerfile'
    tokenPrefix: '__'
    tokenSuffix: '__'

- task: Docker@2
  displayName: login
  inputs:
    containerRegistry: 'JM-ACR-JIOAZURE'
    command: login

# - task: Docker@2
#   displayName: 'BuildDockerImage and Push to JM-ACR-JIOAZURE'
#   inputs:
#     containerRegistry: 'JM-ACR-JIOAZURE'
#     repository: 'myjio-jm/recommendationengine'
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
#     tags: '$(Build.BuildNumber)'    

- task: Docker@2
  displayName: 'BuildDockerImage and Push to JFrogDockerRegistry'
  inputs:
    containerRegistry: 'jfsjpbjfrogregistry'
    repository: '$(RepositoryPath)/recommendationengine'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildNumber)'

- task: CopyFiles@2
  displayName: 'Copy yamls to Artifact staging directory'
  inputs:
    Contents: '*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
